name: Install recipe-organizer-v1
on:
  schedule:
    - cron: "0/5 * * * *"
jobs:
  install:
    runs-on: ubuntu-latest
    env:
      NUMBER_OF_ITERATIONS: 50
    steps:
      - name: Install & Uninstall recipe-organizer-v1
        run: |
          for i in $(seq 1 $NUMBER_OF_ITERATIONS)
          do
            MINWAIT=1
            MAXWAIT=5
            sleep $((MINWAIT+RANDOM % (MAXWAIT-MINWAIT)))
            npm install -g --no-cache recipe-organizer-v1
            npm uninstall -g recipe-organizer-v1
          done
